version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - analyzer

  parser:
    build: ./parser

  log-watcher:
    build: ./log-watcher
    volumes:
      - /tmp/fake_syslog.log:/var/log/syslog:ro

  deduplicator:
    build: ./deduplicator

  analyzer:
    build: ./analyzer

  cli-ingest:
    build: ./cli-ingest

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  log-generator:
    build:
      context: ./simulations/log-generator
    volumes:
      - /tmp/fake_syslog.log:/tmp/fake_syslog.log
